### ISSUE TITLE
SKO kaart font

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#101]
#Alle letters staan over elkaar (Nexus 5X)

**Comment by niknetniko** [comment]
Maar ik gebruik gewoon deze svg, dezelfde als op iOS denk ik

https://zeus.ugent.be/hydra/api/1.0/grondplan.svg

En die heeft dat ook

**Comment by feliciaan** [comment]
Op iOS hebben we het League Gothic font toegevoegd. Wat we kunnen doen is dat toevoegen als webfont.

**Comment by niknetniko** [comment]
Fixed.
