### ISSUE TITLE
Search in activities

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra-android#117]
Make the DSA activities searchable.

While we're at it, investigate if other stuff needs to be searchable as well.

**Comment by feliciaan** [comment]
Maybe add global search functionality?

**Comment by niknetniko** [comment]
Global search could be good, but it is significantly more difficult to implement, because most of the data (activities, schamper, ...) is not necessarily guaranteed to be available offline, so it could take a while to get all data and then search it.

Implementing global search would thus take a fairly big amount of time and effort, so for now I'm thinking to make it a lower priority, since I'm also not sure how useful global search would be (e.g. Minerva isn't all that useful due to the limited data we have access to, same for Schamper)

**Comment by niknetniko** [comment]
Implemented in #186.
