### ISSUE TITLE
retain Minerva course order/cathegories

### ISSUE THREAD

**Issue by NoctuaNivalis** [ZeusWPI/hydra-android#136]
If the API allows this, please retain the Minerva course order and cathegories as set on the website. If not, allow ordering within the app.

Context: As a teacher you can subscribe to different years at the same time, and the courses of 2014 are on top in whichever order is currently used.

**Comment by feliciaan** [comment]
API won't come :(

**Comment by niknetniko** [comment]
😢  The latest beta adds search, but we'll have to add ordering in the app itself as well then

**Comment by niknetniko** [comment]
Re-ordering of the courses will be included in the next beta.
