### ISSUE TITLE
Allow Minerva agenda to be synced to user picked Google account

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/hydra-android#154]
The current functionality lets you sync the Minerva agenda to your systems calendar. However, the behavior now is to add it to a separate 'account' owned by your UGent-mail. Since for a lot of people, their Google  account is not tied to their UGent-mail, this synchronization will not propagate to for example a desktop view of the calendar. To add insult to injury, it does not seem possible to share this agenda with your Google account, because it isn't tied to an account at all (altough requiring to do this is not intended behaviour anyway imo).

**Comment by niknetniko** [comment]
I don't think Hydra is the best way to sync your Minerva calendar with Google; users should do this instead: http://icto.ugent.be/nl/node/33#d.
