### ISSUE TITLE
Provide course-global agenda view

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/hydra-android#155]
For the same reasons as in #153, a global overview would be nice. I discussed this with @niknetniko some time ago and reached to conclusion that this was obsolete since we allow syncing with your device calendar and provide day-by-day collections in the overview. I have however changed my mind in the meanwhile.
I'd like to argue that:
 - Since this is one of out core functionalities now, it would be wise to provide in-app support
 - Not all users use their systems calendar, this way we don't force them to use 2 apps
 - In general we don't require them to take an extra step
 - Some users might not want to sync to their system agenda
 - It would allow us to integrate better with DSA-activities
 - It becomes easier to check some specific dates mentioned in for ex. a notifcation (ex: notification about lesson being moved, people want to check it in their agenda now; they don't have to leave the app this way)

**Comment by niknetniko** [comment]
#295 removed the Minerva integration, meaning this no longer applies. The only event-related code that is left is the DSA activities, which are all shown on one page. A global calendar is therefor no longer necessary.
