### ISSUE TITLE
Urgent.fm doesn't always work on Android O

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra-android#163]
Due to [changes](https://developer.android.com/preview/features/background.html#services) in how foreground services are started in Android O.

Currently we start a foreground service and begin preparing the stream (resolving the audio URL, etc.). Once the stream starts playing, we show the notification and call [`startForeground()`](https://developer.android.com/reference/android/app/Service.html#startForeground(int,android.app.Notification)).

In Android O, we must call `startForeground()` within 5 seconds of starting the service, or the app crashes. The best way to fix this would be showing an notification immediately that says "Preparing" or something like that.

**Comment by wschella** [comment]
I like "tuning in" as a loading message.

**Comment by niknetniko** [comment]
As the documentation has been updated recently, it's not actually necessary to do all that stuff (I think). I'll test some more to make sure, but I'm rewriting a large part of the code anyway, since it wasn't that good.

**Comment by niknetniko** [comment]
Should be fixed, but I'll leave the issue open, because I can't test it, as the emulator no longer works since the latest update `¯\_(ツ)_/¯`

**Comment by niknetniko** [comment]
This was fixed with the latest beta.
