### ISSUE TITLE
Add possibility to sort libraries by campus

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/hydra-android#177]

**Comment by wschella** [comment]
Related to #143

**Comment by niknetniko** [comment]
How would we want this to work exactly? Currently, favourite libraries are first, then they are sorted by name.

This would then sort them favourites first, then by campus and then by name?

An additional question is if this is still needed if the search is implemented?

**Comment by wschella** [comment]
It would come in handy to easily *search* by campus, if that is easy enough, sort by campus might not be necessary. It might remain useful though. The biggest issue it seems is the vast amount of 'libraries', but that is an API problem I guess.

**Comment by wschella** [comment]
I feel like this is no longer relevant since the search is implemented. Campus problem might be captured by #210
