### ISSUE TITLE
Change studentenmobiliteit to fietsambassade

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/hydra-android#190]
Studentenmobiliteit has rebranded to 'De Fietsambassade', in the information/usefull links section we still use 'studentenmobiliteit'

**Comment by niknetniko** [comment]
This information comes from the API, so I have made an issue in there: https://github.com/ZeusWPI/hydra/issues/250

**Comment by wschella** [comment]
Ofcourse, my bad.
