### ISSUE TITLE
Make location clickable in events

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra-android#205]
On the page displaying the event details, the location (nr. 2 in the screenshot) is not clickable. This seems a bit counter-intuitive, and I have witnessed multiple people try to click on it. This should be fairly straightforward to fix, especially since we already have the location data, as shown in the toolbar (1). 

I'm not sure if we should remove the toolbar icon all together once the location is clickable, this is up for debate.

![device-2017-10-13-191910](https://user-images.githubusercontent.com/1756811/31558180-2bf53bfe-b04c-11e7-8f34-88b8a156f187.png)

**Comment by niknetniko** [comment]
The first part of this was implemented in #213.

The question now remains: should the button in the menu remain or should it be removed?

**Comment by wschella** [comment]
We could make the icon the same, or make it more clear the location is clickable. In case 2 I would remove the icon in the toolbar

**Comment by niknetniko** [comment]
I think we should leave the button then, since I don't really know a good way to make it more obvious that the location is clickable.
