### ISSUE TITLE
Add accent colour to schamper categories

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra-android#207]
Schamper articles have a category. On the website, https://www.schamper.ugent.be, every category has it's own colour, e.g. satire is sort of [yellow](https://www.schamper.ugent.be/rubriek/satire).

It might be a nice touch to also tint the category indicator in the app. These colours are not available in the API, so they will have to be hard coded somewhere. There are two possibilities:
- Hard code them at API level by adding another attribute, e.g. `categoryTint` to the API. This will need to be done [in the scraper](https://github.com/ZeusWPI/hydra/blob/master/scraper/schamper.py).
- We can (maybe temporarily) hard code them in the app, for example using string values.

The screenshot below has a red box around the things we would tint:
![device-2017-10-13-194049](https://user-images.githubusercontent.com/1756811/31558907-071cc1d2-b04f-11e7-9aff-6e5db0aceeab.png)

**Comment by redfast00** [comment]
Working on this.

**Comment by redfast00** [comment]
(Almost done, see https://github.com/ZeusWPI/hydra/pull/252)

**Comment by jlpoelma** [comment]
Colors hardcoded in the app

**Comment by niknetniko** [comment]
This has been implemented.
