### ISSUE TITLE
Merge different resto-views

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/hydra-android#233]
I think we should throw the 2 resto-views together.

- With view 1 being the daily overview with a button for the map, the sandwiches, and the week overview.
- With view 2 being the week overview, with navbar with the day, and the ability to select a specific resto.

I propose adding the buttons from view 1 to the bottom of view 2, and only keeping view 2.
I feel we this will greatly simplify some interactions if you don't know the app well, on top it will allow us to remove some code with the same purpose.

**Comment by niknetniko** [comment]
I think this is a good idea.

**Comment by niknetniko** [comment]
Implemented in #234.
