### ISSUE TITLE
RFC: layout upgrade to new UGent colours

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra-android#246]
This issue is to collect feedback. It is a literal _request for comments_.

<hr>

I have recently been working on changing Hydra to use the new UGent colours:
- The blue/yellow tints are now the new UGent blue/yellow colours
- The text is now the default text colour, which is some shade of grey. An advantage is that the app seems more in line with all other apps. Very few apps use coloured text everywhere. This is due to bad contrast resulting in illegible text.

An unintended side effect of this last change is that a dark/night mode became much more doable, so I've added that as well.

Attached screenshots give an idea of the changes, although the best experience would be to run it on your phone. After using it myself for about a month I like the changes, although I am probably biased 😐 .

The older UGent logo was not changed, as this is a delicate matter.

![device-2018-02-03-220433](https://user-images.githubusercontent.com/1756811/35771655-c8c1cc76-0930-11e8-9826-c699123bafbc.png)
![device-2018-02-03-220459](https://user-images.githubusercontent.com/1756811/35771656-c8d8b1ac-0930-11e8-8007-c71ad71e4c5a.png)
![device-2018-02-03-220511](https://user-images.githubusercontent.com/1756811/35771658-c8eec5e6-0930-11e8-9fa3-a5c24266bd76.png)
![device-2018-02-03-220523](https://user-images.githubusercontent.com/1756811/35771659-c90c1f9c-0930-11e8-9618-e9f6dfdd2bb6.png)
![device-2018-02-03-220559](https://user-images.githubusercontent.com/1756811/35771660-c926266c-0930-11e8-878d-5fb376bae2c8.png)
![device-2018-02-03-220611](https://user-images.githubusercontent.com/1756811/35771661-c9411c74-0930-11e8-84b7-a762ee2592f9.png)
![device-2018-02-03-220627](https://user-images.githubusercontent.com/1756811/35771662-c95c8270-0930-11e8-89aa-8bad59bf358a.png)
![device-2018-02-03-220639](https://user-images.githubusercontent.com/1756811/35771663-c9750eda-0930-11e8-8d41-e2559b4982ab.png)

**Comment by niknetniko** [comment]
Things todo:
- [ ] Differentiate bottom bar in resto menu (e.g. grey background in night mode)

**Comment by wschella** [comment]
I think day-mode should be more white. The grey doesn't really fit with ugent blue and yellow (eg. sidenav)

**Comment by wschella** [comment]
For the sidenav, the seperators should be the same style (or maybe we drop them and increase padding). Colors could be okay then, but i'd need to reavaluete. The UGent house-style-light-blue might also be an option in some places.

We might have to check a a more flat layout, no drop shadows on the cards, and thin (or no) border.

**Comment by wschella** [comment]
What I think might work even better:
* make the side-nav UGent-blue
* make font-color and logo blue
* let logo be centered horizontally
* seperators fat, and yellow

I like how this worked out:
[BrugBrochure.pdf](https://github.com/ZeusWPI/hydra-android/files/1925309/BrugBrochure.pdf)

**Comment by niknetniko** [comment]
I'll try to make something similar to see how it looks, but this will be straying a lot from the Material Design guidelines, so we'll have to see how good it looks.

As for the separators, they can be the same colour, but they were intentionally not: the top one was blue to make a sort of continuation of the app bar into the navigation drawer.

Flat cards without drop shadow is not something I would recommend at this time, as the cards are one the most followed aspects of Material Design (on Android), so I think making them substantially different would stand out, but not necessarily in a positive way (it might feel like a cheap imitation of the real cards, like what happens with a lot of cross-platform UI toolkits)

**Comment by wschella** [comment]
I agree with what your saying, but that implies that we should choose between the flat UGent design, or Material Design, mixing both will end up messy.

**Comment by niknetniko** [comment]
Using the native style guidelines on Android (currently Material Design, maybe in the future something else) does have a big advantage: it's a lot less work, since most default or Google-provided UI widgets don't support completely changing the style. I'm also personally a fan of using native styles when possible, but that's not the main factor.

The strategy I've used/am using is applying Material Design with some UGent touches (mainly UGent colours).

Also, a prototype of the blue navigation drawer:
![device-2018-04-18-212130](https://user-images.githubusercontent.com/1756811/38953505-3e3f7694-434f-11e8-8499-b9694c24a046.png)

This does illustrate the point that going against Material Design is a lot of work: using the built-in navigation drawer it's impossible to make both separators fat (only the one on top, but that's because that's a custom separator, and is technically part of the Hydra logo, not the menu itself).

For now I've made the icons just white, since it's impossible to make them blue with a white rectangle around them. To do that, I'd essentially have to create new icons by inverting them, but that's a lot of work for a prototype.

**Comment by wschella** [comment]
I completely understand. My point is that if making the layout coherent is way too much work (which it probably will), I think we should be very conservative with changes. Although the last iterations actually look pretty nice, I think the fact that GH makes these images look very large doesn't contribute positively. 

The white version probably is a decent baseline, altough I am a fan of this blue sidenav! (the white boxes around the logo are not needed definitely)

**Comment by niknetniko** [comment]
I agree with the conservative changes, which is why I didn't change much, apart from the new colours (but this has a big impact on how the app looks).

Perhaps it's better to create an alpha (or new beta) with the layout changes, so interested people can try out the new colours on their device (depending on the screen type and settings, this can vary a lot).

I also like the blue sidenav, so I'll leave it in for now 😄

**Comment by niknetniko** [comment]
As you might have noticed, I have updated the beta to include these layout changes.

**Comment by niknetniko** [comment]
After using the new things for a while, I think the navigation drawer has too much blue.
I therefor propose we change it to something like this:
<a target="_blank" href="https://user-images.githubusercontent.com/1756811/39625627-8d50b18e-4f9e-11e8-82f6-90f3cd8383db.png"><img src="https://user-images.githubusercontent.com/1756811/39625627-8d50b18e-4f9e-11e8-82f6-90f3cd8383db.png" alt="device-2018-05-04-132312" width="350"></a>

**Comment by niknetniko** [comment]
These changes are live now, if we need to tweak them further, we'll open a new issue.
