### ISSUE TITLE
preferences.xml should be in res/xml instead of res/layout

### ISSUE THREAD

**Issue by R13N** [ZeusWPI/hydra-android#25]
Should I change this or not? I originally created this file in `res/xml` but someone moved it.

**Comment by Silox** [comment]
Follow the spec above all else!


On 15 April 2016 at 23:31:49, Rien (notifications@github.com) wrote:

Shoudl I change this or not? I originall created this file in res/xml but someone moved it.

**Comment by feliciaan** [comment]
@R13N in which branch will you be using it? Because it's also "heavily" modified in the `Activities` branch.

**Comment by R13N** [comment]
@feliciaan I am currently using `development`, but if you would like me to use `activities` instead I can switch.

**Comment by feliciaan** [comment]
@R13N maybe use `Activities` because this branch gotten a new theme for the settings.
