### ISSUE TITLE
Wrong snackbar text when displaying main course or soup

### ISSUE THREAD

**Issue by pverscha** [ZeusWPI/hydra-android#289]
When hiding soup or the main course from a resto card on the home screen the message "soep verborgen" appears. But when the soup is shown again, the message is the same and should instead display "soep weergegeven".

**Comment by niknetniko** [comment]
I have confirmed this bug. Thank you for taking the time to report this issue.

**Comment by niknetniko** [comment]
Fixed in #290, will be released in the future.
