### ISSUE TITLE
GSR logo

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra-android#318]
Add the logo of GSR (and maybe Zeus, we'll see) in the navigation bar, since that's a lot more visible then in the settings.

**Comment by niknetniko** [comment]
We should decide where to put it. Is there any idea @NuttyShrimp?

**Comment by NuttyShrimp** [comment]
I think we can start by adding the gsr logo to the about section under the zeus and dsa logo.
If I understand this issue correctly you also want to put the logos elsewhere? Of so, we can maybe put the at the bottom of the navigation/sidebar besides each other

**Comment by niknetniko** [comment]
> If I understand this issue correctly you also want to put the logos elsewhere? Of so, we can maybe put the at the bottom of the navigation/sidebar besides each other

Not necessarily, that depends on how visible the GSR wants their logo.
