### ISSUE TITLE
Fix special characters (see café)

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#35]

**Comment by feliciaan** [comment]
Special chars are working, see some texts, but their is an encoding error between the FK API and the DSA API. Pinging @mlumingu to look after this.

**Comment by mlumingu** [comment]
My web browser also displayed this file incorrectly. I added an .htaccess file in the api dir with "AddCharset UTF-8 .json". Browser now shows the chars correctly. Does this fix the problem on your side?

**Comment by feliciaan** [comment]
I don't see these errors anymore, gonna close the issue :)
