### ISSUE TITLE
Add touch-feedback

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#40]
When I tap on something, I want to have feedback that I have actually tapped.

**Comment by feliciaan** [comment]
What do you mean?

**Comment by Silox** [comment]
See examples at https://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-user-input. This should also happen when I tap on a card (link, event card, ...)

**Comment by niknetniko** [comment]
This should be implemented now.
