### ISSUE TITLE
Consistent interface for resto/activities

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#42]
They both are very similar, but yet they aren't. The sticky header font is bigger on activities, there is no top padding on the activities (while there is some on the resto)

**Comment by feliciaan** [comment]
@eludum do you want to look into this? Take the text size from activities because it s easier readable

**Comment by Silox** [comment]
Or implement https://github.com/ZeusWPI/hydra-android/issues/43 directly and discard this issue :P

**Comment by feliciaan** [comment]
Now they have different styles, both better fitting to their needs.
