### ISSUE TITLE
Stylize sticky headers

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#43]
(#42 related)

The blue bars are just too present, stealing attention away from the content. I propose to follow Google Now's approach as in: 
![screenshot_20160417-214441](https://cloud.githubusercontent.com/assets/915130/14589584/b8d9dc32-04e5-11e6-88d5-c9715eee155e.png)

**Comment by feliciaan** [comment]
No blue bars are used anymore :)
