### ISSUE TITLE
Split up the home view

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#44]
At the moment, there is no clear distinction between the days. I propose to use Google Now's solution to make this more clear: 
![screenshot_20160417-214441](https://cloud.githubusercontent.com/assets/915130/14589601/2be32e22-04e6-11e6-94a5-98bec32f863a.png)

**Comment by NoctuaNivalis** [comment]
I'd also prefer the light rose background for hydra.

**Comment by feliciaan** [comment]
The homeview is not ordered by day but by priority because some cards are not bound to a day, for example the special events, Schamper and news in future versions.

**Comment by feliciaan** [comment]
@Silox what do you think of the current homeview? Because it's currently difficult to split up.

**Comment by Silox** [comment]
@feliciaan Please link a picture.

**Comment by niknetniko** [comment]
Here is a screenshot
![screenshot_20160708-180442](https://cloud.githubusercontent.com/assets/1756811/16693695/b0317aea-4536-11e6-88df-0b7ea87728b7.png)

**Comment by feliciaan** [comment]
@Silox ?
