### ISSUE TITLE
License Hydra for Android

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra-android#444]
For #320, we need to have a formal license, since the code is currently unlicensed.

- I personally like the EUPL, but that's a copyleft license, which is not how Zeus usually licenses stuff.
- Since the Android code was split of from the main repo (which is MIT), the starting code is MIT. This does make our life easier, since all code on first commit is MIT, meaning we can limit our search for authors to this repo. Since it is partially MIT (although unsure how much code survives), it will probably be easier to license everything as MIT.

**In summary: we want to license the code under the MIT license.**

We need to contact each author that contributed to ensure we can license their contribution.

According to `git shortlog -sn`, we have following authors:

- [x]  Niko Strijbol (that's me)
- [x]  Feliciaan De Palmenaer
- [x]  Rien Maertens
- [x]  Mitch De Wilde
- [x]  Ellen Van Hove
- [x]  Tom Naessens
- [x]  Wout Schellaert
- [x]  Michiel Van den Berghe
- [x]  Lukas De Wilde
- [x]  Mehmet Köse
- [x]  Juta Staes
- [x]  Eloïse Piret
- [x]  Niels De Graef
- [x]  ematthie (ewout matt?)
- [x]  Pieter Verschaffelt
- [x]  Titouan Vervack
- [x]  Arthur Vercruysse
- [x]  Felix Van der Jeugt
- [x]  Maxime Bloch
- [x]  Tibo van Heule

For each author, I'll attempt to determine if we need permission, and the contact them. In the first place, I'll do this via e-mail, which leaves a better paper trail of the permissions than various chat apps. If a name is checked, the permission has been obtained (I'll remove unneeded names).

**Comment by feliciaan** [comment]
I approve the use of MIT.

**Comment by Silox** [comment]
I approve the use of MIT.

**Comment by Meddwild** [comment]
I approve the use of MIT

**Comment by ninewise** [comment]
MIT <3 also did I ever work on hydra?

**Comment by niknetniko** [comment]
> MIT <3 also did I ever work on hydra?

Yep, this commit: https://github.com/ZeusWPI/hydra-android/commit/1cfb0ffa75bddcb768f3847be43a97aa8fbb0eb8

**Comment by tibovanheule** [comment]
I approve the use of MIT

**Comment by mivdnber** [comment]
I approve the use of MIT

**Comment by niknetniko** [comment]
Since every contributor has given permission, next steps are:

- Add appropriate copyright header to all files
   - Some files are under the Apache 2.0 license
   - Various icons are Apache 2.0 and/or other licenses.
- Include a LICENSE file
- Mention license in readme
