### ISSUE TITLE
Align left when no picture in activity detail view

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#48]
If there is no image provided for the event, the title and organiser just floats a bit in the center off the page, while the location is left-aligned. Everything should be left-aligned in this case.

**Comment by feliciaan** [comment]
This shouldn't happen, because every association should have a logo. But at the moment some logos for KK and IK associations are missing.

**Comment by feliciaan** [comment]
Find missing logos :( Should be fixed on @ZeusWPI/hydra#239

**Comment by NoctuaNivalis** [comment]
Perhaps this ought to be solved by both fixing the alignment and finding the logo's. While just providing logo's might help now, there're bound to be associations without logo's in the future.

**Comment by feliciaan** [comment]
@niknetniko do you know if this is fixed, because their are currently no events in the DSA API

**Comment by niknetniko** [comment]
This is not fixed yet, I'll look into it

**Comment by niknetniko** [comment]
Fixed with #84
