### ISSUE TITLE
Add possibility to hide a card in the homeactivity

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#50]
2 types of hiding:
- [ ] hide special news (such as the RVB stuff, add something like a x in the right upper corner, or a swype as in google now (with an undo afterwards)
- [x] add specific types of cards (hide all resto, hide all activities, ...), configurable in the settings

**Comment by niknetniko** [comment]
Second item is done

**Comment by niknetniko** [comment]
First part was implemented in #171.
