### ISSUE TITLE
VLK logo isn't transparrent

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#51]
It should be

**Comment by Silox** [comment]
Same for VEK

**Comment by Silox** [comment]
Same for VPPK, same for VTK

**Comment by feliciaan** [comment]
@Silox we know, but FK doesn't have these :(

**Comment by Silox** [comment]
@feliciaan Then we should make them transparent ourself? :)

**Comment by feliciaan** [comment]
Is their someone with PS or GIMP experience who wants to do this?

**Comment by feliciaan** [comment]
Can be closed because it's an issue for the API, [link on hydra-repo](https://github.com/ZeusWPI/hydra/issues/239)
