### ISSUE TITLE
Stylize new icon

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/hydra-android#55]
The new icon looks really great, but it just falls a bit out of the boat, see: 
![screenshot_20160418-081050_1024](https://cloud.githubusercontent.com/assets/915130/14595825/84370c22-0542-11e6-86a2-5b9e56cc257d.png)

We should try different variations: a bit smaller, small rounded corners, ... to make it fit in better

**Comment by NoctuaNivalis** [comment]
Is there a vector/hiRes version of the logo lying around somewhere?

**Comment by feliciaan** [comment]
@NoctuaNivalis [logo](https://github.com/ZeusWPI/hydra/blob/master/iOS/Icons/iTunesArtwork%402x.png)

**Comment by NoctuaNivalis** [comment]
*hiRes*

I'll just make a new vector.

**Comment by niknetniko** [comment]
I would like to propose one of these icons:
![ic_launcher](https://cloud.githubusercontent.com/assets/1756811/16176941/133a68ae-361e-11e6-890c-f9e426ffa99a.png)
![ic_launcher_light](https://cloud.githubusercontent.com/assets/1756811/16176942/13410b78-361e-11e6-9670-45daf80b0ee8.png)

The darker one uses the blue from the official UGent logo, while the lighter one uses the blue from the app (#245b8d).

These icons conform to the [Material Design Icon spec](https://material.google.com/style/icons.html). They were made with the Android Asset Studio (https://romannurik.github.io/AndroidAssetStudio/), with a white version of the UGent logo I made from the official logo.

**Comment by wschella** [comment]
@niknetniko: this issues seems fixed for quite some time. As the current logo is one of those you specified above.
