### ISSUE TITLE
Minerva Integration

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/hydra-android#65]
If someone wants to develop or test to OAuth, PM me so I can share the tokens.

- [x] OAuth prototype
- [x] OAuth login button in home feed
- [x] Add possibility to disable OAuth and Minerva functionality
- [x] OAuth login status in settings (with name)
- [x] OAuth login button in settings
- [ ] Get all courses and make them selectable in settings (like the associations)
- [x] Show recent unread announcements in feed
- [x] Create something to hide announcements (like #50)

**Comment by niknetniko** [comment]
Closing this, as most of it is done.
