### ISSUE TITLE
Hoe verander ik de taal van de app?

### ISSUE THREAD

**Issue by StudentBrocolli** [ZeusWPI/hydra-android#667]
Volgens mij gebruikt de app automatisch de taal van mijn toestel, dat is niet zo handig. En ik versta de naam van sommige recepten niet in het engels. Het zou goed zijn als we de taal kunnen kiezen.

**Comment by niknetniko** [comment]
At the moment, you can't.

While recent androidx libraries do provide an API to create application-level language pickers, this is not something that is currently planned, especially when considering that Android 13 provides system-level support for per-application language preferences.

We still need to opt-in the Android 13 changes, which we will do (tracked in #668).
